# Generated by Django 5.1.4 on 2025-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=150, verbose_name='адрес')),
                ('address', models.CharField(max_length=500, verbose_name='местоположения адресса')),
                ('time_text', models.CharField(max_length=150)),
                ('time_open', models.CharField(max_length=200)),
                ('time_close', models.CharField(max_length=200)),
                ('address_photo', models.ImageField(blank=True, null=True, upload_to='address')),
            ],
        ),
        migrations.CreateModel(
            name='MainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_restaurant', models.CharField(max_length=100, verbose_name='названия ресторана')),
                ('kitchen', models.CharField(max_length=100, verbose_name='кухня')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описания')),
                ('contact_info', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
                ('location_text', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleSecondText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=150, verbose_name='главный текст в середине ')),
                ('description', models.TextField(blank=True, null=True)),
                ('small_text', models.CharField(max_length=25, verbose_name='маленький тест сверху')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleTitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=150, verbose_name='главный текст в середине ')),
                ('description', models.TextField(blank=True, null=True)),
                ('small_text', models.CharField(max_length=25, verbose_name='маленький тест сверху')),
            ],
        ),
    ]
