# Generated by Django 5.2 on 2025-04-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_name_en', models.CharField(max_length=100, null=True)),
                ('category_name_ru', models.CharField(max_length=100, null=True)),
                ('category_name_ky', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('category_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('extra_name', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_name_ky', models.CharField(blank=True, max_length=100, null=True)),
                ('item_connect', models.ManyToManyField(blank=True, null=True, related_name='extra', to='menu.menuitem')),
            ],
        ),
    ]
