# Generated by Django 5.2 on 2025-04-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_name_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='extra_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extras',
            name='item_connect',
            field=models.ManyToManyField(blank=True, related_name='extra', to='menu.menuitem'),
        ),
    ]
