# Generated by Django 5.2 on 2025-04-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=150, verbose_name='адрес')),
                ('address_text_en', models.CharField(max_length=150, null=True, verbose_name='адрес')),
                ('address_text_ru', models.CharField(max_length=150, null=True, verbose_name='адрес')),
                ('address_text_ky', models.CharField(max_length=150, null=True, verbose_name='адрес')),
                ('address', models.CharField(max_length=500, verbose_name='местоположения адресса')),
                ('address_en', models.CharField(max_length=500, null=True, verbose_name='местоположения адресса')),
                ('address_ru', models.CharField(max_length=500, null=True, verbose_name='местоположения адресса')),
                ('address_ky', models.CharField(max_length=500, null=True, verbose_name='местоположения адресса')),
                ('time_text', models.CharField(max_length=150)),
                ('time_text_en', models.CharField(max_length=150, null=True)),
                ('time_text_ru', models.CharField(max_length=150, null=True)),
                ('time_text_ky', models.CharField(max_length=150, null=True)),
                ('time_open', models.CharField(max_length=200)),
                ('time_open_en', models.CharField(max_length=200, null=True)),
                ('time_open_ru', models.CharField(max_length=200, null=True)),
                ('time_open_ky', models.CharField(max_length=200, null=True)),
                ('time_close', models.CharField(max_length=200)),
                ('time_close_en', models.CharField(max_length=200, null=True)),
                ('time_close_ru', models.CharField(max_length=200, null=True)),
                ('time_close_ky', models.CharField(max_length=200, null=True)),
                ('address_photo', models.ImageField(blank=True, null=True, upload_to='address')),
            ],
        ),
        migrations.CreateModel(
            name='MainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_restaurant', models.CharField(max_length=100, verbose_name='названия ресторана')),
                ('name_restaurant_en', models.CharField(max_length=100, null=True, verbose_name='названия ресторана')),
                ('name_restaurant_ru', models.CharField(max_length=100, null=True, verbose_name='названия ресторана')),
                ('name_restaurant_ky', models.CharField(max_length=100, null=True, verbose_name='названия ресторана')),
                ('kitchen', models.CharField(max_length=100, verbose_name='кухня')),
                ('kitchen_en', models.CharField(max_length=100, null=True, verbose_name='кухня')),
                ('kitchen_ru', models.CharField(max_length=100, null=True, verbose_name='кухня')),
                ('kitchen_ky', models.CharField(max_length=100, null=True, verbose_name='кухня')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описания')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='описания')),
                ('description_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='описания')),
                ('description_ky', models.CharField(blank=True, max_length=250, null=True, verbose_name='описания')),
                ('contact_info', models.CharField(max_length=150)),
                ('contact_info_en', models.CharField(max_length=150, null=True)),
                ('contact_info_ru', models.CharField(max_length=150, null=True)),
                ('contact_info_ky', models.CharField(max_length=150, null=True)),
                ('number', models.CharField(max_length=50)),
                ('location_text', models.CharField(max_length=25)),
                ('location_text_en', models.CharField(max_length=25, null=True)),
                ('location_text_ru', models.CharField(max_length=25, null=True)),
                ('location_text_ky', models.CharField(max_length=25, null=True)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(max_length=25)),
                ('small_text_en', models.CharField(max_length=25, null=True)),
                ('small_text_ru', models.CharField(max_length=25, null=True)),
                ('small_text_ky', models.CharField(max_length=25, null=True)),
                ('text', models.CharField(max_length=250)),
                ('text_en', models.CharField(max_length=250, null=True)),
                ('text_ru', models.CharField(max_length=250, null=True)),
                ('text_ky', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleSecondText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=150, verbose_name='главный текст в середине ')),
                ('main_text_en', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('main_text_ru', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('main_text_ky', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('small_text', models.CharField(max_length=25, verbose_name='маленький тест сверху')),
                ('small_text_en', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
                ('small_text_ru', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
                ('small_text_ky', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleTitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=150, verbose_name='главный текст в середине ')),
                ('main_text_en', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('main_text_ru', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('main_text_ky', models.CharField(max_length=150, null=True, verbose_name='главный текст в середине ')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('small_text', models.CharField(max_length=25, verbose_name='маленький тест сверху')),
                ('small_text_en', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
                ('small_text_ru', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
                ('small_text_ky', models.CharField(max_length=25, null=True, verbose_name='маленький тест сверху')),
            ],
        ),
    ]
