# Generated by Django 5.2 on 2025-04-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintitle',
            name='location_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='location_ky',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='location_ru',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
